" minimal config without any large dependencies

so ~/.sshrc.d/.vimrc

" Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle-managed plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
" Plugins for specific filetypes
Plugin 'Vimjas/vim-python-pep8-indent'
Plugin 'LnL7/vim-nix'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line

" Plugin-specific configuration
runtime plugin-configs/nerdtree.vim
runtime plugin-configs/ctrlp.vim
runtime plugin-configs/syntastic.vim

" Language-specific configuration
filetype plugin indent on
