" minimal config without any large dependencies

so ~/.sshrc.d/.vimrc

" Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

let g:ackprg = 'ag --vimgrep'

" Vundle-managed plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-commentary'
" Plugin 'skwp/greplace.vim'
Plugin 'mileszs/ack.vim'
Plugin 'tpope/vim-surround'
Plugin 'vim-scripts/ScrollColors'
Plugin 'godlygeek/tabular'

" Plugins for specific filetypes
Plugin 'Vimjas/vim-python-pep8-indent'
Plugin 'LnL7/vim-nix'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'plasticboy/vim-markdown'
Plugin 'idris-hackers/idris-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line

" Plugin-specific configuration
runtime plugin-configs/nerdtree.vim
runtime plugin-configs/ctrlp.vim
runtime plugin-configs/syntastic.vim

" Language-specific configuration
filetype plugin indent on

" functions
function! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

" Syntax changes
highlight link jsxRegion String

set nofoldenable
